add a new attribute user agent
don't know why unit tests are failing

Step 9/11 : RUN python -m unittest discover --verbose
 ---> Running in 69cce631957c
test_constructor (test.testMyMessage.MyMessageTestCase) ... ok
test_create_random_message (test.testMyMessage.MyMessageTestCase) ... ok
test_create_random_messages (test.testMyMessage.MyMessageTestCase) ... ok
test_load_from_json (test.testMyMessage.MyMessageTestCase) ... /var/www/backend/test/testMyMessage.py:27: ResourceWarning: unclosed file <_io.TextIOWrapper name='sample/example.json' mode='r' encoding='UTF-8'>
  data = json.load(open("sample/example.json"))
ok
test_sanity_check_my_parser (test.testMyParser.TfIdfTestCase) ... ok
test_constructor (test.testMyVisitor.MyVisitorTestCase) ... FAIL
test_score_over_negative_one (test.testTfIdf.TfIdfTestCase) ... ok
test_score_under_one (test.testTfIdf.TfIdfTestCase) ... ok

======================================================================
FAIL: test_constructor (test.testMyVisitor.MyVisitorTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/www/backend/test/testMyVisitor.py", line 24, in test_constructor
    self.assertEqual(my_visitor.url, "/test-address")
AssertionError: ('/test-address',) != '/test-address'

----------------------------------------------------------------------
Ran 8 tests in 1.024s

FAILED (failures=1)
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
messages
View my Pics Now. It's Free!
View my Pics Now. It's Free! View my Pics Now. It's Free!
Top words in document 1
	Word: Social, TF-IDF: 0.03772
	Word: social, TF-IDF: 0.03772
	Word: From, TF-IDF: 0.02368
	Word: records, TF-IDF: 0.01886
	Word: Kushal, TF-IDF: 0.01886
	Word: Ashamed, TF-IDF: 0.01886
	Word: Enter, TF-IDF: 0.01886
	Word: E-mail, TF-IDF: 0.01886
	Word: View, TF-IDF: 0.01886
	Word: Profiles, TF-IDF: 0.01886
Top words in document 2
	Word: To, TF-IDF: 0.0364
	Word: score, TF-IDF: 0.0273
	Word: Kushal, TF-IDF: 0.02209
	Word: Your, TF-IDF: 0.02209
	Word: Dec, TF-IDF: 0.0182
	Word: 2017, TF-IDF: 0.0182
	Word: 16:14:54, TF-IDF: 0.0182
	Word: 0600, TF-IDF: 0.0182
	Word: Ashamed, TF-IDF: 0.01473
	Word: Social, TF-IDF: 0.01473
Top words in document 3
	Word: To, TF-IDF: 0.03699
	Word: Kushal, TF-IDF: 0.01995
	Word: Click, TF-IDF: 0.01995
	Word: score, TF-IDF: 0.01849
	Word: Is, TF-IDF: 0.01521
	Word: Ashamed, TF-IDF: 0.01496
	Word: unsubscribe, TF-IDF: 0.01496
	Word: DailyDeal, TF-IDF: 0.01496
	Word: LLC, TF-IDF: 0.01496
	Word: 11923, TF-IDF: 0.01496
Top words in document 4
	Word: To, TF-IDF: 0.03916
	Word: Kushal, TF-IDF: 0.02218
	Word: Click, TF-IDF: 0.02218
	Word: City, TF-IDF: 0.01803
	Word: Ashamed, TF-IDF: 0.01584
	Word: city, TF-IDF: 0.01449
	Word: unsubscribe, TF-IDF: 0.01268
	Word: DailyDeal, TF-IDF: 0.01268
	Word: LLC, TF-IDF: 0.01268
	Word: 11923, TF-IDF: 0.01268
Top words in document 5
	Word: To, TF-IDF: 0.04311
	Word: Kushal, TF-IDF: 0.02035
	Word: Click, TF-IDF: 0.02035
	Word: City, TF-IDF: 0.01654
	Word: Ashamed, TF-IDF: 0.01453
	Word: city, TF-IDF: 0.01329
	Word: unsubscribe, TF-IDF: 0.01163
	Word: DailyDeal, TF-IDF: 0.01163
	Word: LLC, TF-IDF: 0.01163
	Word: 11923, TF-IDF: 0.01163
Top words in document 6
	Word: OF, TF-IDF: 0.0865
	Word: The, TF-IDF: 0.0343
	Word: CONGO, TF-IDF: 0.02768
	Word: Congo, TF-IDF: 0.02768
	Word: KABILA, TF-IDF: 0.02768
	Word: Kabila, TF-IDF: 0.02768
	Word: the, TF-IDF: 0.02746
	Word: YOUR, TF-IDF: 0.0271
	Word: In, TF-IDF: 0.02439
	Word: WE, TF-IDF: 0.02076
Top words in document 7
	Word: My, TF-IDF: 0.03746
	Word: As, TF-IDF: 0.03173
	Word: The, TF-IDF: 0.0213
	Word: Now, TF-IDF: 0.01983
	Word: my, TF-IDF: 0.01967
	Word: the, TF-IDF: 0.01705
	Word: I, TF-IDF: 0.01612
	Word: charity, TF-IDF: 0.01586
	Word: life, TF-IDF: 0.0119
	Word: less, TF-IDF: 0.0119
Top words in document 8
	Word: i, TF-IDF: 0.05942
	Word: the, TF-IDF: 0.03275
	Word: client, TF-IDF: 0.01981
	Word: US, TF-IDF: 0.01552
	Word: Agabi, TF-IDF: 0.01486
	Word: agabi, TF-IDF: 0.01486
	Word: All, TF-IDF: 0.01486
	Word: Since, TF-IDF: 0.01486
	Word: next, TF-IDF: 0.01486
	Word: Mr, TF-IDF: 0.01164
Top words in document 9
	Word: AND, TF-IDF: 0.07603
	Word: The, TF-IDF: 0.04038
	Word: the, TF-IDF: 0.03233
	Word: YOUR, TF-IDF: 0.02836
	Word: Abacha, TF-IDF: 0.01448
	Word: Security, TF-IDF: 0.01418
	Word: You, TF-IDF: 0.01209
	Word: security, TF-IDF: 0.0114
	Word: Mohammed, TF-IDF: 0.01086
	Word: Also, TF-IDF: 0.01086
Top words in document 10
	Word: Of, TF-IDF: 0.04821
	Word: The, TF-IDF: 0.03866
	Word: the, TF-IDF: 0.03095
	Word: Us, TF-IDF: 0.02552
	Word: interested, TF-IDF: 0.01702
	Word: Account, TF-IDF: 0.01702
	Word: This, TF-IDF: 0.01523
	Word: MY, TF-IDF: 0.01333
	Word: us, TF-IDF: 0.01303
	Word: would, TF-IDF: 0.0125
Top words in document 11
	Word: ayy, TF-IDF: 0.9359
	Word: lmao, TF-IDF: 0.9359
Top words in document 12
	Word: drcep, TF-IDF: 0.02753
	Word: nioahnqw, TF-IDF: 0.02753
	Word: narxbd, TF-IDF: 0.02753
	Word: wgd, TF-IDF: 0.02753
	Word: ysmiu, TF-IDF: 0.02753
	Word: hbplfufm, TF-IDF: 0.02753
	Word: gabldc, TF-IDF: 0.02753
	Word: mip, TF-IDF: 0.02753
	Word: ipzzf, TF-IDF: 0.02753
	Word: mtpgkour, TF-IDF: 0.02753
Top words in document 13
	Word: IN, TF-IDF: 0.04505
	Word: In, TF-IDF: 0.03529
	Word: The, TF-IDF: 0.03215
	Word: the, TF-IDF: 0.02574
	Word: Your, TF-IDF: 0.02538
	Word: World, TF-IDF: 0.02458
	Word: WORLD, TF-IDF: 0.02458
	Word: BANK, TF-IDF: 0.02458
	Word: UNITED, TF-IDF: 0.02048
	Word: Contact, TF-IDF: 0.02048
Top words in document 1
	Word: Social, TF-IDF: 0.03772
	Word: social, TF-IDF: 0.03772
	Word: From, TF-IDF: 0.02368
	Word: records, TF-IDF: 0.01886
	Word: Kushal, TF-IDF: 0.01886
	Word: Ashamed, TF-IDF: 0.01886
	Word: Enter, TF-IDF: 0.01886
	Word: E-mail, TF-IDF: 0.01886
	Word: View, TF-IDF: 0.01886
	Word: Profiles, TF-IDF: 0.01886
Top words in document 2
	Word: To, TF-IDF: 0.0364
	Word: score, TF-IDF: 0.0273
	Word: Kushal, TF-IDF: 0.02209
	Word: Your, TF-IDF: 0.02209
	Word: Dec, TF-IDF: 0.0182
	Word: 2017, TF-IDF: 0.0182
	Word: 16:14:54, TF-IDF: 0.0182
	Word: 0600, TF-IDF: 0.0182
	Word: Ashamed, TF-IDF: 0.01473
	Word: Social, TF-IDF: 0.01473
Top words in document 3
	Word: To, TF-IDF: 0.03699
	Word: Kushal, TF-IDF: 0.01995
	Word: Click, TF-IDF: 0.01995
	Word: score, TF-IDF: 0.01849
	Word: Is, TF-IDF: 0.01521
	Word: Ashamed, TF-IDF: 0.01496
	Word: unsubscribe, TF-IDF: 0.01496
	Word: DailyDeal, TF-IDF: 0.01496
	Word: LLC, TF-IDF: 0.01496
	Word: 11923, TF-IDF: 0.01496
Top words in document 4
	Word: To, TF-IDF: 0.03916
	Word: Kushal, TF-IDF: 0.02218
	Word: Click, TF-IDF: 0.02218
	Word: City, TF-IDF: 0.01803
	Word: Ashamed, TF-IDF: 0.01584
	Word: city, TF-IDF: 0.01449
	Word: unsubscribe, TF-IDF: 0.01268
	Word: DailyDeal, TF-IDF: 0.01268
	Word: LLC, TF-IDF: 0.01268
	Word: 11923, TF-IDF: 0.01268
Top words in document 5
	Word: To, TF-IDF: 0.04311
	Word: Kushal, TF-IDF: 0.02035
	Word: Click, TF-IDF: 0.02035
	Word: City, TF-IDF: 0.01654
	Word: Ashamed, TF-IDF: 0.01453
	Word: city, TF-IDF: 0.01329
	Word: unsubscribe, TF-IDF: 0.01163
	Word: DailyDeal, TF-IDF: 0.01163
	Word: LLC, TF-IDF: 0.01163
	Word: 11923, TF-IDF: 0.01163
Top words in document 6
	Word: OF, TF-IDF: 0.0865
	Word: The, TF-IDF: 0.0343
	Word: CONGO, TF-IDF: 0.02768
	Word: Congo, TF-IDF: 0.02768
	Word: KABILA, TF-IDF: 0.02768
	Word: Kabila, TF-IDF: 0.02768
	Word: the, TF-IDF: 0.02746
	Word: YOUR, TF-IDF: 0.0271
	Word: In, TF-IDF: 0.02439
	Word: WE, TF-IDF: 0.02076
Top words in document 7
	Word: My, TF-IDF: 0.03746
	Word: As, TF-IDF: 0.03173
	Word: The, TF-IDF: 0.0213
	Word: Now, TF-IDF: 0.01983
	Word: my, TF-IDF: 0.01967
	Word: the, TF-IDF: 0.01705
	Word: I, TF-IDF: 0.01612
	Word: charity, TF-IDF: 0.01586
	Word: life, TF-IDF: 0.0119
	Word: less, TF-IDF: 0.0119
Top words in document 8
	Word: i, TF-IDF: 0.05942
	Word: the, TF-IDF: 0.03275
	Word: client, TF-IDF: 0.01981
	Word: US, TF-IDF: 0.01552
	Word: Agabi, TF-IDF: 0.01486
	Word: agabi, TF-IDF: 0.01486
	Word: All, TF-IDF: 0.01486
	Word: Since, TF-IDF: 0.01486
	Word: next, TF-IDF: 0.01486
	Word: Mr, TF-IDF: 0.01164
Top words in document 9
	Word: AND, TF-IDF: 0.07603
	Word: The, TF-IDF: 0.04038
	Word: the, TF-IDF: 0.03233
	Word: YOUR, TF-IDF: 0.02836
	Word: Abacha, TF-IDF: 0.01448
	Word: Security, TF-IDF: 0.01418
	Word: You, TF-IDF: 0.01209
	Word: security, TF-IDF: 0.0114
	Word: Mohammed, TF-IDF: 0.01086
	Word: Also, TF-IDF: 0.01086
Top words in document 10
	Word: Of, TF-IDF: 0.04821
	Word: The, TF-IDF: 0.03866
	Word: the, TF-IDF: 0.03095
	Word: Us, TF-IDF: 0.02552
	Word: interested, TF-IDF: 0.01702
	Word: Account, TF-IDF: 0.01702
	Word: This, TF-IDF: 0.01523
	Word: MY, TF-IDF: 0.01333
	Word: us, TF-IDF: 0.01303
	Word: would, TF-IDF: 0.0125
Top words in document 11
	Word: ayy, TF-IDF: 0.9359
	Word: lmao, TF-IDF: 0.9359
Top words in document 12
	Word: drcep, TF-IDF: 0.02753
	Word: nioahnqw, TF-IDF: 0.02753
	Word: narxbd, TF-IDF: 0.02753
	Word: wgd, TF-IDF: 0.02753
	Word: ysmiu, TF-IDF: 0.02753
	Word: hbplfufm, TF-IDF: 0.02753
	Word: gabldc, TF-IDF: 0.02753
	Word: mip, TF-IDF: 0.02753
	Word: ipzzf, TF-IDF: 0.02753
	Word: mtpgkour, TF-IDF: 0.02753
Top words in document 13
	Word: IN, TF-IDF: 0.04505
	Word: In, TF-IDF: 0.03529
	Word: The, TF-IDF: 0.03215
	Word: the, TF-IDF: 0.02574
	Word: Your, TF-IDF: 0.02538
	Word: World, TF-IDF: 0.02458
	Word: WORLD, TF-IDF: 0.02458
	Word: BANK, TF-IDF: 0.02458
	Word: UNITED, TF-IDF: 0.02048
	Word: Contact, TF-IDF: 0.02048
ERROR: Service 'backend_app' failed to build: The command '/bin/sh -c python -m unittest discover --verbose' returned a non-zero code: 1